---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 27h
  url: https://kubernetes-sigs.github.io/metrics-server
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: monitoring
  install:
    createNamespace: true
  upgrade:
    preserveValues: false
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: '3.8.4'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 1m
  values:
    apiService:
      create: true
    extraArgs:
          - --kubelet-preferred-address-types=InternalIP
          - --kubelet-insecure-tls=true
