---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: odb-dev
  secretRef:
    name: flux-system
  url: ssh://git@gitlab.com/odba1/kubernetes.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
