apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
  labels:
    app: ingress-nginx
spec:
  targetNamespace: default
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.7.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
      admissionWebhooks:
        failurePolicy: Ignore
      config:
        use-proxy-protocol: "true"
        use-forwarded-headers: "false"
        real-ip-header: proxy_protocol
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      ingressClassResource:
        name: nginx
        enabled: true
        defaut: true
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 12
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 50
        behavior:
          scaleUp:
            policies:
            - type: Pods
              value: 1
              periodSeconds: 60
          scaleDown:
            policies:
            - type: Pods
              value: 1
              periodSeconds: 60
      resources:
        requests:
          memory:	200Mi
          cpu: 100m
        limits:
          memory: 1000Mi
          cpu: 1000m





