apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-stack
  releaseName: loki
  targetNamespace: logging
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: '2.9.9'
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 60m
  values:
    promtail:
      labels:
        app: promtail
        release: loki-stack
    loki:
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 100Gi
      ingress:
        enabled: false
        annotations:
          kubernetes.io/backend.protocol: HTTPS
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: monitoring-odb-dev.itoutposts.ltd
            paths:
              - /
        tls:
          - secretName: monitoring-dev-tls-cert
            hosts:
              - monitoring-odb-dev.itoutposts.ltd
      serviceMonitor:
        enabled: false
        additionalLabels:
          release: monitoring-kube-prometheus-stack
        annotations:
          release: monitoring-kube-prometheus-stack
      config:
        limits_config:
          reject_old_samples: false
        table_manager:
          retention_deletes_enabled: true
          retention_period: 336h
    grafana:
      enabled: false
    prometheus:
      enabled: false
