---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 27h
  url: https://charts.bitnami.com/bitnami
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-postgresql-dev
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      version: 12.4.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m
  targetNamespace: dev-database
  install:
    createNamespace: true
  upgrade:
    preserveValues: false
  values:
    image:
      tag: "12.14.0"
    auth:
      username: "dev_odb_user"
      database: "dev-odb"	
      existingSecret: "postresql-secret"
