apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  interval: 27h
  url: http://charts.gitlab.io/
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  dependsOn:
    - name: aws-ebs-csi-driver
  targetNamespace: gitlab-runner
  install:
      createNamespace: true
  upgrade:
    preserveValues: false
  interval: 5m
  chart:
    spec:
      chart: gitlab-runner
      version: '0.53.0'
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
        namespace: flux-system
      interval: 1m
  values:
    gitlabUrl: https://gitlab.com/
    runners:
      secret: gitlab-runner-secret
      tags: "kube-runner"
      config: |
        [[runners]]
          [runners.kubernetes]
            image = "ubuntu:20.04"
            privileged = true
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-certs"
            mount_path = "/certs/client"
            medium = "Memory"
    rbac:
      create: true
      rules:
      - resources: ["configmaps", "pods", "pods/attach", "secrets", "services"]
        verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create", "patch", "delete"]

        
      
