# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: HelmRepository
# metadata:
#   name: sonarqube
#   namespace: flux-system
# spec:
#   interval: 27h
#   url: https://SonarSource.github.io/helm-chart-sonarqube
#   timeout: 2m
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: sonarqube
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: aws-ebs-csi-driver
#   targetNamespace: sonarqube
#   install:
#       createNamespace: true
#   upgrade:
#     preserveValues: false
#   interval: 5m
#   chart:
#     spec:
#       chart: sonarqube
#       version: '10.0.0+521'
#       sourceRef:
#         kind: HelmRepository
#         name: sonarqube
#         namespace: flux-system
#       interval: 1m
#   # values:
#   #   installCRDs: true