apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 27h
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  targetNamespace: kube-system
  upgrade:
    preserveValues: false
  interval: 5m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: '2.17.1'
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      interval: 1m
  values:
    controller:
      serviceAccount:
        create: false
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
        tolerationSeconds: 300
    node:
      tolerateAllTaints: true
      tolerations:
      - operator: Exists
        effect: NoExecute
        tolerationSeconds: 300






    