---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: stack
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://git@github.com/popilmv/stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: stack
