apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
  interval: 10m
  timeout: 5m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        enabled: true
        hosts:
          - grafana.mari1327.pp.ua
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        folder: /tmp/dashboards
        folderAnnotation: grafana_folder
        provider:
          allowUiUpdates: true
          foldersFromFilesStructure: true
          updateIntervalSeconds: 30
      datasources:
        enabled: true
        label: grafana_datasource
    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100






