apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 1m
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  targetNamespace: default
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: '1.5.2'
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
        namespace: flux-system
      interval: 1m
  values:
    clusterName: odb-dev
    region: us-east-1
    vpcId: vpc-0c53e754bb425d76c
    serviceAccount:
      create: true