apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 27h
  url: https://charts.external-secrets.io/
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
  labels:
    app: external-secrets
spec:
  dependsOn:
    - name: aws-ebs-csi-driver
  targetNamespace: external-secrets
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  releaseName: external-secrets
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: '0.8.3'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 1m
