apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 27h
  url: https://stakater.github.io/stakater-charts
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
  labels:
    app: reloader
spec:
  dependsOn:
    - name: aws-ebs-csi-driver
  targetNamespace: reloader
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  releaseName: reloader
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: '1.0.28'
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
      interval: 1m
